export const MYSQL_FUNCTIONS = new Set([
  'ASCII', 'CHAR_LENGTH', 'CHAR', 'CONCAT', 'CONCAT_WS', 'ELT', 'EXPORT_SET',
  'FIELD', 'FIND_IN_SET', 'FORMAT', 'INSERT', 'INSTR', 'LCASE', 'LEFT', 'LENGTH',
  'LOCATE', 'LOWER', 'LPAD', 'LTRIM', 'MID', 'POSITION', 'REPEAT', 'REPLACE',
  'REVERSE', 'RIGHT', 'RPAD', 'RTRIM', 'SPACE', 'STRCMP', 'SUBSTR', 'SUBSTRING',
  'SUBSTRING_INDEX', 'TRIM', 'UCASE', 'UPPER',

  'ABS', 'ACOS', 'ASIN', 'ATAN', 'ATAN2', 'CEIL', 'CEILING', 'CONV', 'COS',
  'COT', 'CRC32', 'DEGREES', 'DIV', 'EXP', 'FLOOR', 'LN', 'LOG', 'LOG10',
  'LOG2', 'MOD', 'PI', 'POW', 'POWER', 'RADIANS', 'RAND', 'ROUND', 'SIGN',
  'SIN', 'SQRT', 'TAN', 'TRUNCATE',

  'ADDDATE', 'ADDTIME', 'CURDATE', 'CURRENT_DATE', 'CURRENT_TIME',
  'CURRENT_TIMESTAMP', 'CURTIME', 'DATE', 'DATEDIFF', 'DATE_ADD', 'DATE_FORMAT',
  'DATE_SUB', 'DAY', 'DAYNAME', 'DAYOFMONTH', 'DAYOFWEEK', 'DAYOFYEAR', 'EXTRACT',
  'FROM_DAYS', 'FROM_UNIXTIME', 'GET_FORMAT', 'HOUR', 'LAST_DAY', 'LOCALTIME',
  'LOCALTIMESTAMP', 'MAKEDATE', 'MAKETIME', 'MICROSECOND', 'MINUTE', 'MONTH',
  'MONTHNAME', 'NOW', 'PERIOD_ADD', 'PERIOD_DIFF', 'QUARTER', 'SECOND',
  'SEC_TO_TIME', 'STR_TO_DATE', 'SUBDATE', 'SUBTIME', 'SYSDATE', 'TIME',
  'TIME_FORMAT', 'TIME_TO_SEC', 'TIMEDIFF', 'TIMESTAMP', 'TO_DAYS', 'UNIX_TIMESTAMP',
  'UTC_DATE', 'UTC_TIME', 'UTC_TIMESTAMP', 'WEEK', 'WEEKDAY', 'WEEKOFYEAR',
  'YEAR', 'YEARWEEK',

  'AVG', 'BIT_AND', 'BIT_OR', 'BIT_XOR', 'COUNT', 'GROUP_CONCAT', 'MAX', 'MIN',
  'STD', 'STDDEV', 'SUM', 'VAR_POP', 'VAR_SAMP', 'VARIANCE',

  'CASE', 'IF', 'IFNULL', 'NULLIF',

  'JSON_ARRAY', 'JSON_OBJECT', 'JSON_EXTRACT', 'JSON_UNQUOTE', 'JSON_ARRAYAGG',
  'JSON_CONTAINS', 'JSON_KEYS', 'JSON_LENGTH', 'JSON_MERGE', 'JSON_REMOVE',
  'JSON_REPLACE', 'JSON_SET', 'JSON_TYPE', 'JSON_VALID',

  'MD5', 'SHA1', 'SHA2', 'AES_ENCRYPT', 'AES_DECRYPT', 'UNCOMPRESS', 'UNCOMPRESSED_LENGTH',

  'DATABASE', 'USER', 'VERSION', 'FOUND_ROWS', 'LAST_INSERT_ID', 'ROW_COUNT',

  'INET_ATON', 'INET_NTOA', 'UUID', 'BENCHMARK', 'SLEEP', 'CONNECTION_ID'
]);